<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_688c2b87c4b37',
	'title' => 'testing one',
	'fields' => array(
		array(
			'key' => 'field_688c2b88f376e',
			'label' => '',
			'name' => '',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'rows' => 10,
			'placeholder' => '',
			'new_lines' => 'wpautop',
		),
		array(
			'key' => 'field_68924659c3651',
			'label' => 'select one',
			'name' => 'select_one',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'one' => 'First one (condition, true)',
				'two' => 'second (false)',
				'three' => 'Third one, also true',
				'four' => 'Fourth, also false',
				'five' => 'and one more true for good measure',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_689246bac3652',
			'label' => 'conditional something',
			'name' => 'conditional_something',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_68924659c3651',
						'operator' => '==',
						'value' => 'one',
					),
				),
				array(
					array(
						'field' => 'field_68924659c3651',
						'operator' => '==',
						'value' => 'three',
					),
				),
				array(
					array(
						'field' => 'field_68924659c3651',
						'operator' => '==',
						'value' => 'five',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_689e6a4a36c72',
			'label' => 'Max height',
			'name' => 'max_height',
			'aria-label' => '',
			'type' => 'range',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 75,
			'min' => 40,
			'max' => 90,
			'allow_in_bindings' => 0,
			'step' => '',
			'prepend' => '',
			'append' => '% of viewport height',
		),
		array(
			'key' => 'field_689e6c4b36c73',
			'label' => 'Full width slides',
			'name' => 'full_width_slides',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'style' => 'rounded',
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_display_title' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1755226314,
));

endif;